### ISSUE TITLE
Unit displaying white light and chimes when no power.

### ISSUE THREAD

**Issue by BilliTheKid** [dride/dride-app-issues#11]
It seems when no power is given to my Dride it still displays a white light momentarily then goes off then there is a chime that comes from it. You cannot connect to it via the app but this white LED on/off and chime goes on for a while after the power has been totally removed from the unit. I mean over an hour or two. I have a video recording acting like this but I cannot seem to post it here.

**Comment by JerryBlack** [comment]
Might be related to its internal battery?  "Dride have a small battery for internal purposes, it can hold up to a few minutes of recording time. When the battery dies there will be issues with time savings but this should take 3+ years until it does"

**Comment by ntnlabs** [comment]
For me, this happens when Dride decides it wont record anything. When I shut down my car it works for 20+ minues and then shuts off.

**Comment by BilliTheKid** [comment]
@JerryBlack @ntnlabs Interesting.

@saoron Is this normal? Is it meant to still draw power after it has been disconnected? Surely for non hardwired users this could cause a problem with the internal battery. For those connected via USB this will occur everytime the engine is turned off?

**Comment by ntnlabs** [comment]
It's not everytime for me. More like 1 in 10. If I dont connect the app and dont press the Share button it works as "expected"... PS: I'm on the lighter power.

**Comment by BilliTheKid** [comment]
@ntnlabs So it is happening? It seems everytime the mini USB is disconnected it happens so it has to be a bug. Hopefully @saoron will provide more information.

**Comment by saoron** [comment]
This happens when the dashcam freezes, it shouldn't be happening, Danifelty something we're looking into.

**Comment by BilliTheKid** [comment]
@saoron OK great. Looking forward to the fix

**Comment by BilliTheKid** [comment]
Seems new firmware resolves this issue.. Closing this thread
