### ISSUE TITLE
Dride gets stuck after first video rotation

### ISSUE THREAD

**Issue by ntnlabs** [dride/dride-app-issues#12]
This is to inform that my dride behaves like this:
- engine starts, dride starts (chime, white light)
- phone connects to the wifi (app not started)
- dride starts recording
- after approx 1 minute, or 5 minutes (depends on my settings) dride goes to green and stops recording
- next is one of three scenarios
-- I reset the dride with share button
-- I open the app
-- I pull the power

None of these resolves the problem 100%. Most of the time the app works,  after I open the app the app "sets" the dride unit again and it starts to record again. When I reset the dride unit, it usually resumes and records the rest of my journey. The power is the worst, but sometimes the others do not work.

**Comment by saoron** [comment]
What FW are you on?

**Comment by ntnlabs** [comment]
The original one. The one that the unit was shipped with. Is there a new one?

**Comment by saoron** [comment]
Could you please install the latest beta and recheck?

**Comment by ntnlabs** [comment]
Gonna do that today.

[ntn]

**Comment by saoron** [comment]
Please reopen if needed.
