### ISSUE TITLE
Dride shuts off a fter continuous usage

### ISSUE THREAD

**Issue by ntnlabs** [dride/dride-app-issues#13]
After approx 90 minutes the unit usually shuts down. Light goes off and recording stops.

**Comment by saoron** [comment]
Are you connected via the fuse box cable?

**Comment by ntnlabs** [comment]
I am on a lighter cable.

**Comment by saoron** [comment]
Is the green LED on the power outlet is lit?

**Comment by ntnlabs** [comment]
Dont remember, but I think Yes. Will try to check.

[ntn]

**Comment by saoron** [comment]
Please test on new firmware and re-open if needed.
