### ISSUE TITLE
Video cycle length bug

### ISSUE THREAD

**Issue by ntnlabs** [dride/dride-app-issues#14]
Dride starts to record videos in files that are one second long (instead of 1 minute, or 5 minutes). Usually happens after the first video cycle.

**Comment by BilliTheKid** [comment]
Yes I have noticed this bug too. @saoron

**Comment by saoron** [comment]
Confirmed, Will be fixed on the next app version.

Thanks for reporting

**Comment by BilliTheKid** [comment]
@saoron When is the next Android app release due?

**Comment by BilliTheKid** [comment]
@saoron New app update has connection issues to Android.

**Comment by BilliTheKid** [comment]
Clip length bug still present. Clip lengths of only 22 seconds.

**Comment by saoron** [comment]
One thing to notice when checking the clip length is when you open the app a video clips is closed, so if you open the app 22 seconds into the clip you will get a 22 seconds long clip, Try to keep it running without opening the app and it will normalize..
