### ISSUE TITLE
Issues with compression when trying to share by email, WhatsApp etc

### ISSUE THREAD

**Issue by BilliTheKid** [dride/dride-app-issues#15]

**Comment by BilliTheKid** [comment]
The higher the resolution the worst it is. The compression used makes the video clip very blurry and hard to make out things.

**Comment by saoron** [comment]
We've just released v5.8.1 for Android, this should be fixed.
I'll keep this open until you verify..

Thanks,

**Comment by BilliTheKid** [comment]
Perfect thanks @saoron Will report back

**Comment by BilliTheKid** [comment]
Continue to app v 5.9.3
