### ISSUE TITLE
Firmware version number??

### ISSUE THREAD

**Issue by MyDefender** [dride/dride-app-issues#18]
I’m trying to update the firmware to the latest version on Github (2.0-beta-1) [https://github.com/dride/dride-app-issues/releases/tag/2.0-beta-1](url). After updating and deleting the 'bin' file, the light stays red/white rather than pure white though and the firmware version says ‘DrideZero_V0.0.1’. Is that the correct or should the firmware version number be different? And why does the light not go pure white?

**Comment by saoron** [comment]
This is a confirmed bug in the new Beta, Thanks for reporting this..

**Comment by MyDefender** [comment]
OK, thank you.

**Comment by MyDefender** [comment]
Ok, thanks.

**Comment by MyDefender** [comment]
Do you mean the red/white light is the bug or the firmware version number or both? What should the firmware version number be for (a) the latest beta and (b) the original?

**Comment by gaurav85** [comment]
How do you upload the beta firmware?

**Comment by MyDefender** [comment]
Put the 'bin' file on the root of the SD card and turn on your Dride. Power up the Dride. It will blink red and eventually turn white. Then re-insert the SD to your computer and remove the 'bin' file.

**Comment by saoron** [comment]
Fixed on 1.1-beta-2
