### ISSUE TITLE
No speed or GPS data when playing back exported video

### ISSUE THREAD

**Issue by MyDefender** [dride/dride-app-issues#19]
Using the latest Beta firmware, there is no GPS or speed data when playing back a video file. I downloaded the file to my phone and exported it to my laptop. I used the HQBKING player [https://master.dl.sourceforge.net/project/windows-hqbking-player/HQBKING%20Player20181107_134400.zip](url)
On the plus side, I now have a pure white light, connection to my phone (iOS) seems quicker and more stable and the forward-facing video is correctly orientated.

![2019-11-15 (1)_LI](https://user-images.githubusercontent.com/56696655/68970314-dbccfd00-07de-11ea-9760-1a3f3aaef800.jpg)

**Comment by saoron** [comment]
It might take a few hours until the Dride get a GPS fix (on first boot, later this should take a minute or two)
I suggest to wait a bit until you get a fix.

Re-open if needed,
