### ISSUE TITLE
Downloading Events, stops after first SAVE

### ISSUE THREAD

**Issue by trancen** [dride/dride-app-issues#2]
Loading the app, I can download/SAVE one EVENT and then when I try to SAVE another one to the phone it stays at 0% of the transfer. 
The get around this. I FORCE close the app , restart and it will download the second EVENT clip that was stuck at 0%.... If I try to download a 3rd clip(after the first FORCE CLOSE) it does the same and stays at 0%.

Android Pixel 3 XL, Android 10.xx running the 5.5.1 of the Dride app.

**Comment by saoron** [comment]
This is a confirmed and fixed bug, thanks for reporting! Check out the change log for our gratitude ;)
