### ISSUE TITLE
Unable to connect with 5.8.2

### ISSUE THREAD

**Issue by trancen** [dride/dride-app-issues#20]
Since the update to 5.8.2 Andriod 10.xx on a pixel 3xl I haven't been able to connect to the dride.  I have deleted the cache, uninstalled. Deleted the wifi connection ... Held the cloud for several seconds.  And just stays at the "connecting .. " message on the application

**Comment by BilliTheKid** [comment]
@trancen Yes I'm getting the same too.

**Comment by saoron** [comment]
Thanks for reporting about this guys, We're pushing a fix right now..

https://dride.io/forum/critical-bug-in-android-live-thread____BuTHv5hGJJfUQ28O3rPU
