### ISSUE TITLE
New app update just hangs on connecting

### ISSUE THREAD

**Issue by BilliTheKid** [dride/dride-app-issues#21]
Since updating to the new app 5.8.2 it just hangs and won't connect to the unit now. Something wrong there @saoron Even cleared cache and data and still nothing.
![Screenshot_20191116-123951](https://user-images.githubusercontent.com/56843472/68993325-9eb04b80-086e-11ea-9f12-f24458e5791e.png)

**Comment by saoron** [comment]
merge with #20
