### ISSUE TITLE
v5.3.8 still has issues

### ISSUE THREAD

**Issue by BilliTheKid** [dride/dride-app-issues#22]
New app still has connectivity issues. Updated and it connected once. All the videos wouldn't play so I came out of the app and went back in again and the connectivity problems are there again. 
![Screenshot_20191116-144501](https://user-images.githubusercontent.com/56843472/68994968-7af60100-0880-11ea-843b-a8322a1f07ed.png)

**Comment by BilliTheKid** [comment]
Got it to work after a forced reset of the device. Issues still with clip length and video's deleting and coming back. @saoron

**Comment by trancen** [comment]
The first time I was able to connect. The second time I got in the car it connected but took a while for it to make the connect it was stuck on the "connecting ...." Screen ...can also confirm that the delete of the event videos dont delete

**Comment by BilliTheKid** [comment]
@trancen @saoron Yes clip still issues connecting, clip length and deletion of videos too.

**Comment by BilliTheKid** [comment]
Issues still: @saoron 

• Clip length only 22secs.
• Issues with deleting video's and reappearing again.
• Compression for sharing video still not fixed.
• Pressing sharing does nothing.

**Comment by BilliTheKid** [comment]
Update:

Not sure but now the videos are at 3 mins as set.
When playing video it seems to buffer alot.
Event video's when deleted still come back.
Compression is still poor when sharing.
Uploading video to share is slow.
When pressing the share button nothing is captured to share on the dashboard.

**Comment by BilliTheKid** [comment]
Update:

Clips now at desired length which is 3 minutes for me.
The light now for whatever reason is a white/red. It wasn't like this before.
Share button doesn't seem to do anything.
Compression still heavily compressed when sharing.
Sharing video is very slow including downloading video.
Tried hard resetting the unit a few times with no success on the above.

**Comment by BilliTheKid** [comment]
@saoron

**Comment by BilliTheKid** [comment]
So installed the Dride today and brought it for a test drive and pressed the share button a few times to test. So got home,turned off the car and went inside. Launched app and there is no videos for me to view. Any ideas @saoron 


![Screenshot_20191119-171619](https://user-images.githubusercontent.com/56843472/69169730-c1ea2d80-0af0-11ea-84ef-befe9534b83a.png)

**Comment by saoron** [comment]
This screen is for videos stored in the cloud, When you press the button those "events" will be locked on the SD card and you will see them on the first row of the video feed.

Later on they will be downloaded locally to your device and you will receive a push notification about it. The only way videos will end up in the "cloud" page is when you choose to share a video.

**Comment by BilliTheKid** [comment]
Ok I'm home over an hour and nothing has still come up under video's or no push notifications. Any suggestions? @saoron

**Comment by BilliTheKid** [comment]
Continue on to v5.9.3
