### ISSUE TITLE
Issues for 1.1-beta-2

### ISSUE THREAD

**Issue by JerryBlack** [dride/dride-app-issues#23]
@saoron  Sorry these are not separated, but never-the-less...    Issues for 1.1-beta-2 emailed 3:14 am AST Nov 19 2019. using App Version iOS 5.8.1

Changed:
 App reports v1.1, SSID is back to being Dride...  Light is now white rather than white/red.

New: 
1) Rear camera view is now inverted (wrong in my case). Note my rear camera is installed with the cable to exiting upwards, for proper fitment. If this isn't the assumed orientation, you need a user option to invert the image.

Existing:
1) Time is off (maybe just because the GPS hasn't locked yet?, but the vehicle is in open air). Time has been correct in the past, and previously it seemed to correct itself after a period of time.
2) Video resolution can be changed, but does not stick according to the menu.
3) Deleted videos come back when you launch the app again.

Untested:
1) Sharing
2) Shared Video quality
3) Clip length (3 min) respected

Thanks for the option to test and provide feedback.

**Comment by BilliTheKid** [comment]
@JerryBlack @saoron Where is this latest Beta?

**Comment by JerryBlack** [comment]
@billiTheKid https://github.com/dride/dride-app-issues/releases/tag/1.1-beta-2 <https://github.com/dride/dride-app-issues/releases/tag/1.1-beta-2>
as far as I know.

**Comment by BilliTheKid** [comment]
Thanks @JerryBlack I'll flash it. I've reported some issues that I have experienced to @saoron on the App 5.38 thread.

**Comment by BilliTheKid** [comment]
@JerryBlack Just tested and fixes the light issue. Haven't had a chance to test any other improvements. Question. Can you view any of your recordings when you are not connected to Dride? It seems I must stay in my car, view the recordings, and then share while the unit is powered on.

**Comment by BilliTheKid** [comment]
Updated to new app. @saoron No videos have still not appeared in my video's or no push notification

**Comment by ntnlabs** [comment]
I confirm that the rear video is upside down. Gonna test other things tomorrow.

One more "bug": can't set anything. Everytime I change anything in app the app hangs on "updating" screen. And the live view acts funny, but I take that as a glitch, reporting anyway.
![Screenshot_20191119-222736](https://user-images.githubusercontent.com/26405113/69189338-79496900-0b1e-11ea-8d0a-d52aa3ef1157.png)
![Screenshot_20191119-222808](https://user-images.githubusercontent.com/26405113/69189340-79496900-0b1e-11ea-93a8-7aba02867fd3.png)
![Screenshot_20191119-222902](https://user-images.githubusercontent.com/26405113/69189341-79e1ff80-0b1e-11ea-8a9a-b3a02267d990.png)
![Screenshot_20191119-222942](https://user-images.githubusercontent.com/26405113/69189342-79e1ff80-0b1e-11ea-9468-1406e489f02f.png)

**Comment by JerryBlack** [comment]
@BilliTheKid I don't have the workflow figured out for sharing / viewing videos. A video that I saved to my iPhone (I don't remember offhand which action did this) and is visible through the normal "Photos" app is also visible through the Dride app through the "My Videos" menu item even when not connected to the dridezero..  I have successfully shared a video to the dride.io for testing as well in the past.

**Comment by BilliTheKid** [comment]
@JerryBlack @ntnlabs @saoron 

Updated to new app 5.9.2

So the bugs for me are:
No video's appearing in my videos. Can only view video's through the app when connected to the unit. Yossi states these should appear after sometime but they don't.
No push notifications to state video's have downloaded to videos.
Timestamp is wrong again for my region.
Compression for sharing video still bad.
Video's still not deleting.

The Red banner in the app stating connect to Dride isn't very visually appealing. I'd rethink that or remove it.

**Comment by ntnlabs** [comment]
Okay so real world test of this build revealed one more issue: dRide  is randomly turning off and on. With the sound. It goes like this: dRide starts, recording starts, light goes from green to white. Then after 1-15 minutes a chime is played and the light goes to green. Then the light goes to white again and the whole process repeats. I would mark this as !IMPORTANT, I feel like I'm gonna downgrade the firmware.

**Comment by BilliTheKid** [comment]
@ntnlabs @saoron 

Just been out for a drive and no shutdown for me. What I have found in this firmware update is that the connection time from the unit to the app is alot slower than the previous firmware. Approximately 12/15 seconds. Other issues I've mentioned above too that need to be fixed. Also would like a toggle to be able to turn the start up/shutdown chime to be turned on/off.

**Comment by BilliTheKid** [comment]
Still none of my videos are captured in my videos after my drive today. @saoron 
![Screenshot_20191120-130156](https://user-images.githubusercontent.com/56843472/69245559-edc3ec80-0b9e-11ea-88e7-95ad126366a2.png)

**Comment by BilliTheKid** [comment]
![Screenshot_20191120-130147](https://user-images.githubusercontent.com/56843472/69245577-f74d5480-0b9e-11ea-8c5f-b58c94a57086.png)

**Comment by ntnlabs** [comment]
Okay, so yesterday I was driving a bit more (approx. 7 hrs). The first 1 hour or so there were shutdowns, but the I had two long rides (approx. 3 hrs each) and the camera behaved nice. No shutdowns and steady white light. Gonna check how was the recording, but... Dunno what to think.

Has anyone considered a developer edition of firmware that would log alot and then the user would like send the logs back? I volunteer if needed.

**Comment by BilliTheKid** [comment]
Another test today now running current beta firmware and app 5.92

Bugs still in place.

• Connection time to app is slower than before
• Viewing captured video's seems to be buffering constantly even on 4G.
• No video's loaded into my videos after trip to view.
• Video's will not delete.
• Compression for sharing still needs fixing.
• Download of videos at 3 minutes long is very slow.
• Uploading sharing videos is extremely slow.
• Time is still wrong.
• Thumbnails of video clips not showing.

Things I'd like to see implemented or changed.

• Option to toggle start up/shutdown chime.
• Option to auto delete videos after a certain amount of days.
• LIVE view to be enabled in landscape to view journey. This feature is shown on the campaign page in 16x9 format fitting a phone screen.
• Removal of red connect banner.
• Emergency SOS message/text if in collision.
• Quick easy release from windscreen when not in use to avoid theft.
• Automatic uploads to my videos when in use. 
• Photo Mode.

I would really like to add the rear camera to my unit but only if it can be installed within the car.
@saoron @JerryBlack @ntnlabs

**Comment by BilliTheKid** [comment]
Video's buffering when try to view from within the app.

![Screenshot_20191121-105657](https://user-images.githubusercontent.com/56843472/69338605-7607c780-0c5b-11ea-908d-5fb890d7d2fd.png)

**Comment by BilliTheKid** [comment]
Campaign page shows LIVE view in 16X9 (Landscape) but it's not currently available in the app.

![Uploading Screenshot_20191121-124506.png…]()

**Comment by BilliTheKid** [comment]
@JerryBlack @ntnlabs Do you have any videos saved in my videos when you are disconnected from Dride to view?

**Comment by JerryBlack** [comment]
I have 2 videos visible “in the cloud “ back from Nov 6th when I probably purposefully saved them to the cloud.

**Comment by BilliTheKid** [comment]
@JerryBlack Are they in here?
![Screenshot_20191121-182437](https://user-images.githubusercontent.com/56843472/69365423-373e3580-0c8c-11ea-925e-8b9c52e6db7b.png)

**Comment by JerryBlack** [comment]
They are, but they did not get their automatically.

**Comment by BilliTheKid** [comment]
@JerryBlack How did you get them to appear there? I've had none of my footage appear there. I can only view clips when connected to Dride or download them to my phone.

@saoron Yossi any idea what's going on? You stated they should download automatically and get a push notification but this has not happened.

**Comment by JerryBlack** [comment]
Hi,

OK, Just tested again. I went to the car and joined the dride wifi network, and launched the app.  I chose a video that was recorded today and clicked on share. That gave me a sharing page where the “Other” icon was highlighted. I clicked on the upload banner at the bottom and it uploaded it to to https://dride.io/clip/Cl2HtnFkbvnxjmWNIPUk <https://dride.io/clip/Cl2HtnFkbvnxjmWNIPUk>  I presume it used my cellular data for that :( 

That video is now visible in my “My Videos in The Cloud” via “My Videos” menu.

Cheers

**Comment by BilliTheKid** [comment]
@JerryBlack I presumed all your recording videos would appear there from your trips. That would make better sense to view in your house. I think a feature to do that should be out in place. Also an auto delete of the videos that are over a certain amount of days to free up room on the SD. It's a pain to just be able to view my recordings only when I'm connected to the unit

**Comment by JerryBlack** [comment]
My impression is that sharing is not automatic, which makes sense given the relatively low % of video that one might want to spend money on to upload (and share).  I also suspect not everything is implemented yet.

The videos are individually saveable to your phone (in my case iPhone Photos) in a similar share fashion as save to dride.io, and my thoughts are that I would choose what to do with noteworthy video on a case by case basis. I would most likely choose to save to the phone and then process them in my normal workflow for phone videos.

An accident recording suggests you should share it to the cloud so it can’t be destroyed as easily.  Then of course, people to like to share video of other drivers behaving badly.

Having a pick-list of videos to save to your phone, would streamline uploading a sequence of videos from a noteworthy scenic drive.


Interesting (to me) today I could observe just how little time the rust proofing crew spent on my car while it was in the shop having an annual rust proofing check :)

**Comment by BilliTheKid** [comment]
@JerryBlack OK so I have uploaded 2 videos. And yes they appear in my videos but its a shame they cannot be automatically in my device on the fly to view later when I get home. It means I must be in my car Uploading and sharing videos. Also the loading of the thumbnail videos are very slow too. Are you having issues with that?

**Comment by BilliTheKid** [comment]
![Screenshot_20191121-205413](https://user-images.githubusercontent.com/56843472/69376933-26e58500-0ca3-11ea-894b-888caaf9a8cd.png)
![Screenshot_20191121-205433](https://user-images.githubusercontent.com/56843472/69376940-2cdb6600-0ca3-11ea-93e2-1afcb1932b8e.png)

**Comment by BilliTheKid** [comment]
![Screenshot_20191121-154621](https://user-images.githubusercontent.com/56843472/69376970-3bc21880-0ca3-11ea-8e28-9f83b91c5605.png)

**Comment by JerryBlack** [comment]
Yes it would be nice if it were automatic, but that might be a lot of storage space over a day (I haven’t done the math) for your phone.

For a while, initially, I could logon to the dride from my portable in the house while the dride was in the car.  I can’t seem to do that now, even when the network is visible. Then I could choose to download all the videos (previewing was not possible0.

The thumbnails do take a while, but I’m forgiving of that, as they are fairly high res videos and you’re asking a lot to get the file back to the phone over 2.4Ghz for preview. When viewed in landscape mode it looks to me that they may not have been downsampled (I can’t tell). 

Cheers

**Comment by BilliTheKid** [comment]
@JerryBlack Gotcha. Yes would be nice to have them visible on my phone. Still a few bugs which I outlined to @saoron so hopefully he'll address them soon. How did you manage to view them from your house?

One more question. You have the rear camera yet? Is this only mountable to the outside of your vehicle?

**Comment by JerryBlack** [comment]
How long does the video preview take to download for you? (and what length of video)?

**Comment by BilliTheKid** [comment]
@JerryBlack Over 4G and at top resolution and say 15 to 20 seconds, it can take sometimes up to 3/5 mins. It's very slow to get to 50% then it flies to a 100% in under a minute.

**Comment by JerryBlack** [comment]
I have the rear camera, and I mounted inside my Outback to the ceiling just at the rear hatch. There’s no way here in Nova Scotia an external camera would be usable, as this way there is a window and rear wiper between it and the rain/snow. I did my own wiring along the ceiling to the back and didn’t have to snake into the trunk hatch (the provided cable wasn’t quite long enough anyway to make it into the hatch).

**Comment by BilliTheKid** [comment]
@JerryBlack How was it mounted to the roof? By 3M tape? Can it be mounted to the back windshield?

**Comment by JerryBlack** [comment]
The supplied tape (and I must confess 2 tiny screws) into ceiling fabric.

I’m not sure about the windsheild, it would probably depend on the angle. I think it arrived configured to be attached to a window, but I flipped the support bracket so the camera could point outwards.

**Comment by BilliTheKid** [comment]
@JerryBlack @saoron 

How can I get a rear camera please?

**Comment by BilliTheKid** [comment]
@JerryBlack All is gone quiet from Yossi.

Have you noticed any bug fixes, improvements, changes with app version 5.9.3?

They got rid of the red connect banner which was a good move.

**Comment by JerryBlack** [comment]
I’m on an iPhone, which has a slower update/approval process. I haven’t seen 5.9.3 appear yet.

**Comment by BilliTheKid** [comment]
@JerryBlack Ah right. From my testing it doesn't seem to have squashed any of the bugs I have reported to @saoron It's hard to know as there is no logs reported on each update to state what's been done.

**Comment by BilliTheKid** [comment]
@JerryBlack Opened up a thread on 5.9.3 on issues and what I'd like to see implemented and known bugs.Add at will.

**Comment by BilliTheKid** [comment]
@JerryBlack @saoron Is there an other firmware update on the way to test?

**Comment by BilliTheKid** [comment]
@saoron @JerryBlack Time stamp still out and having issues saving vids too.
![Screenshot_20191125-185300](https://user-images.githubusercontent.com/56843472/69569175-ff4d3000-0fb4-11ea-9fb4-b9dd2a2743e6.png)
![Screenshot_20191125-184523](https://user-images.githubusercontent.com/56843472/69569180-04aa7a80-0fb5-11ea-925c-bd98dee8e7ce.png)
