### ISSUE TITLE
32 GB sd cards

### ISSUE THREAD

**Issue by ntnlabs** [dride/dride-app-issues#24]
Are 32 GB cards supported? Because I could not flash from one, I had to get a 16 GB one. The same manufacturer BTW...

**Comment by JerryBlack** [comment]
@ntnlabs 32 GB cards are the max size supported according to the Setup Guide (in the app).

**Comment by BilliTheKid** [comment]
@ntnlabs Yep 32GB is the limit. I found in the past some dashcams don't work well with different manufacturers SD cards. Best getting one that plays well with dashcams. After alot of trial and error, this one for me is the best. Transcend High Endurance 32GB Class 10

**Comment by saoron** [comment]
Thanks for answering.

Closed.
