### ISSUE TITLE
Various Bugs Need Fixing

### ISSUE THREAD

**Issue by BilliTheKid** [dride/dride-app-issues#25]
Just recieved the update with no user logs.

@saoron Can you tell me what has changed/fixed and implemented with this version please? Has any of the bugs I've highlighted been addressed?

**Comment by BilliTheKid** [comment]
![Screenshot_20191122-183022](https://user-images.githubusercontent.com/56843472/69451765-0f1c0880-0d58-11ea-8ad3-803c89103d04.png)

Reported bugs so far.

• For some reason even though the clip lengths are set to 3 mins they are only recording for 1.30
• Time is still wrong.
• Date should be set by region. e.g. day/month/year for EU countries and month/day/year for US.
(Please see screenshot)

**Comment by BilliTheKid** [comment]
Bugs to be addressed (continued)

• Connection time to app is slower than before
• Viewing captured video's seems to be buffering constantly even on 4G
• Compression for sharing still needs fixing.
• Download of videos at 3 minutes long is very slow.
• Uploading sharing videos is extremely slow.
• GPS and speed not showing on recent Recordings.

Things I'd like to see implemented or changed.

• Option to toggle start up/shutdown chime.
• Option to auto delete videos after a certain amount of days. (3,5,10,15,30)
• LIVE view to be enabled in landscape to view journey. This feature is shown on the campaign page in 16x9 format fitting a phone screen.
• Emergency SOS message/text or push notification if in collision.
• Quick easy release from windscreen when not in use to avoid theft.
• Automatic uploads to my videos when in use. 
• Photo Mode. (Press sharing button twice to take a photo)
• Auto back up feature to save videos to Google Drive,Dropbox,Box etc.
• Give the user the option to change time and date format.

**Comment by BilliTheKid** [comment]
Another trip today. GPS and speed no longer shows on recording @saoron 

![Screenshot_20191123-171637](https://user-images.githubusercontent.com/56843472/69482607-777cef80-0e15-11ea-941f-81914f74223f.png)

**Comment by BilliTheKid** [comment]
@saoron Any update on the above bugs?

**Comment by BilliTheKid** [comment]
Is there somewhere I can purchase the rear camera please? @saoron

**Comment by BilliTheKid** [comment]
• Deleting event videos still reappear after you reopen the app. @saoron

**Comment by saoron** [comment]
Thank you for posting this issues here, we read all posts but can't comment on a post with many issues,
We will address any issue we find, In the future please open a new thread for each issue.

Thanks for posting this ❤️

**Comment by BilliTheKid** [comment]
@saoron I have.
