### ISSUE TITLE
Timestamp still messed up

### ISSUE THREAD

**Issue by gaurav85** [dride/dride-app-issues#26]
Even with the latest app version and firmware timestamp is still messed up. Check the attached screenshot. It was taken at 8:43 AM Central Time in US on 26th November 2019.
![28B3D5A5-EC32-4319-85D8-25A55B80E47B](https://user-images.githubusercontent.com/8796616/69643623-36f5bf80-1029-11ea-8477-b7fab9a6d009.png)

**Comment by JerryBlack** [comment]
Although it may not be your problem, it was noted that the device may take a while to gain a GPS lock and location. I see that you’re “underground” so maybe that is an issue?

**Comment by BilliTheKid** [comment]
@JerryBlack Mine is out too. I've been testing it for the past 3 days and the timestamp is incorrect

**Comment by saoron** [comment]
Guys, could you please test this firmware and let me know if the time issue is still there?
[FW96663A.bin.zip](https://github.com/dride/dride-app-issues/files/3896397/FW96663A.bin.zip)

**Comment by BilliTheKid** [comment]
Can confirm it fixes the timestamp and you can also delete videos and they stay deleted. However there is a small bug in settings when you try and change settings that the updating wheel just constantly goes around and around. If you close the app and go back into it, it has changed but when you change another setting it happens again with it going around and around and you must close out of the app in order for the change to be implemented. It wasn't like this before. Connection time could be quicker too. And there are a few other bugs.@saoron 
![Screenshot_20191127-111202](https://user-images.githubusercontent.com/56843472/69719121-bf4a9200-1107-11ea-9453-24bfec027be4.png)
![Screenshot_20191127-110651](https://user-images.githubusercontent.com/56843472/69719133-c5407300-1107-11ea-990b-7d25d7e5b4c7.png)

**Comment by saoron** [comment]
Fixed on the latest public version (1.2)
