### ISSUE TITLE
No in-app notifications on iOS

### ISSUE THREAD

**Issue by MyDefender** [dride/dride-app-issues#29]
Since installing the Dride in my car three weeks ago I have not had any in-app notifications at all. What notifications are we supposed to get? On iOS 13.2.3, latest version of Dride app and 1.1-Beta-2 firmware.

**Comment by BilliTheKid** [comment]
@MyDefender Only in app notification I get on Android is when I download a video to my phone. That's it.

**Comment by saoron** [comment]
When a video is download in the background a notification is sent.
