### ISSUE TITLE
Firmware 1.2-beta-0

### ISSUE THREAD

**Issue by ntnlabs** [dride/dride-app-issues#30]
First of all, lightning fast connection from the app, congrats :)
 - cannot check the live view, cannot confirm rear view fixed
 - still video after first loop makes many tiny files
 - still saving settings from Settings menu takes ages (or is not working)
- I think the 10sec-share-button reset is not working

- one good feature at this stage would be to show full firmware and all other info info in the "about this device" screen
- please name every release with new file name, right now it's the same only size is different

**Comment by BilliTheKid** [comment]
Add these to the list.

• No GPS stamp on recordings.

• No speed stamp on recordings.

• Connection time to app is slower than before. Sometimes you have to open app to connect but not all the time.

• Changing settings has the updating wheel going around for ages  (FIXED)

• Sharing button records only a few seconds and does not automatically upload to cloud as advertised. Sharing does not download to phone either.

• Deleting event videos reappear after app is reopened.

• Viewing captured video's seems to be buffering at times even on 4G.

• Compression for sharing still needs fixing.

• Download of videos at 3 minutes long is very slow.

• Uploading sharing videos is extremely slow.

(Things I'd like to see implemented or changed)

• Option to toggle start up/shutdown chime.

• Option to auto delete videos after a certain amount of days. (3,5,10,15,30)

• LIVE view to be enabled in landscape to view journey. This feature is shown on the campaign page in 16x9 format fitting a phone screen.

• Emergency SOS message/text or push notification if in collision.

• Quick easy release from windscreen when not in use to avoid theft.

• Automatic uploads to my videos when in use. 

• Photo Mode. (Press sharing button twice to take a photo)

• Auto back up feature to save videos to Google Drive,Dropbox,Box etc.

• Give the user the option to change time and date format.

@saoron

**Comment by BilliTheKid** [comment]
![Screenshot_20191127-200722](https://user-images.githubusercontent.com/56843472/69761384-26476580-115f-11ea-8f3a-ed8a971b7eec.png)

No GPS or Speed stamp

**Comment by saoron** [comment]
Thank you for posting this issues here, we read all posts but can't comment on a post with many issues, 
We will address any issue we find, In the future please open a new thread for each issue.

Thanks for posting this ❤️
