### ISSUE TITLE
Firmware 1.2-beta-0 - unable to save a video

### ISSUE THREAD

**Issue by JerryBlack** [dride/dride-app-issues#31]
I don't appear to be able to save a clip.

If this isn't a bug, this message indicates that I just tried to upload too soon.  How long should one expect to wait before uploading?

![IMG_9344](https://user-images.githubusercontent.com/2327941/69756002-def5b080-112f-11ea-8486-464951521572.PNG)
![IMG_9345](https://user-images.githubusercontent.com/2327941/69756027-ecab3600-112f-11ea-88f9-9a0f566e7b9d.PNG)

**Comment by BilliTheKid** [comment]
@JerryBlack I was getting that yesterday too. I can download videos to my phone though.

**Comment by saoron** [comment]
This might happen if connection is interpreted between the camera and your phone, Did you tried again? Same issue?

**Comment by JerryBlack** [comment]
@BilliTheKid @saoron I tried this morning and it works until it gets to 60% at which point it says saving video to library, then it just stalls (repeatedly). There is 20G free on the iPhone. 

Alternately, "Other"   (saving to dride.io) works without a problem.  I notice that this mode has a transcoding step (or something worded like that) that I didn't see as part of the "Save" progress.

![IMG_9348](https://user-images.githubusercontent.com/2327941/69812373-68f05880-11c6-11ea-93f4-f49ea9c3a4b2.PNG)

**Comment by BilliTheKid** [comment]
@JerryBlack @saoron Saving to the device for me is fine with Android but saving up the cloud results in the same issue of timing out too. Head scratcher.

**Comment by JerryBlack** [comment]
@saoron @BilliTheKid Just went out and tried again. Saving worked this time, go figure. I have reduced my recording length back to 1 minute to make saving more responsive.

**Comment by BilliTheKid** [comment]
@JerryBlack @saoron Still a bug though. You shouldn't have to set it to a minute.
