### ISSUE TITLE
Firmware 1.2-beta-0 - Date/Time stamps are correct but a bad time video was generated.

### ISSUE THREAD

**Issue by JerryBlack** [dride/dride-app-issues#32]
Just an observation that after the firmware update, the system recorded a video in the future, but quickly established the correct date/time for subsequent videos. 

This isn't a new bug, but I suspect as these videos in the future continue to show up at the head of the list of videos, that some people may not notice that the videos further down the screen actually have the correct date/time (once the GPS fix is established) [an assumption on my part].

I was able to delete this bad time video, but **still not able to delete Event videos** (as reported earlier by BilliTheKid)

**Comment by BilliTheKid** [comment]
I thought this was just me but yes this is a minor bug @JerryBlack  Also no GPS or speed recorded on videos either. Still some other bugs to iron out too. @saoron

**Comment by JerryBlack** [comment]
@BilliTheKid I am getting date/time/location and speed on my stored videos. 

[Edit] After posting, I've just noticed that my location is off by about 25 km. Maybe the GPS on the video I peaked at hadn't resolved itself yet.
[Edit 2] I was mixed up - the GPS values as displayed are correct, but the time is off.

**Comment by BilliTheKid** [comment]
It wasn't working yesterday but it is now with GPS and speed being back but now the time is off by 1 hour @JerryBlack @saoron I think a user option to set time and date manually might be a better.

![Screenshot_20191128-150419](https://user-images.githubusercontent.com/56843472/69816478-630f6d00-11f0-11ea-8f80-5002d4ea4f2e.png)

**Comment by BilliTheKid** [comment]
There is also a minor bug with background connectivity on Android with the app were I need to open the app for it to connect to the Dride which it didn't have to do before. @JerryBlack @saoron

**Comment by saoron** [comment]
Anyone can confirm that the time bug is resolved starting from v1.2?

**Comment by BilliTheKid** [comment]
@saoron I will check on the way to work later and report back.

**Comment by BilliTheKid** [comment]
@JerryBlack @saoron This bug is still there as of today. On the latest app and firmware. The first few videos times are completely wrong then after a while it sorts itself out. But again this is a bug for sure.
![Screenshot_20191203-133345](https://user-images.githubusercontent.com/56843472/70057831-bc531400-15d5-11ea-90ba-0858fed67d75.png)
![Screenshot_20191203-133337](https://user-images.githubusercontent.com/56843472/70057843-c117c800-15d5-11ea-857d-a83375c5f76c.png)

**Comment by saoron** [comment]
merge with #43
