### ISSUE TITLE
Firmware 1.2-beta-0 - display of latitude/longitude 

### ISSUE THREAD

**Issue by JerryBlack** [dride/dride-app-issues#33]
The latitude longitude values currently display as dd.mmxxxx.   
Previously they were ddmm.xxxx
both are subject to misinterpretation at 1st glance, but I presume if they represent degrees and decimal minutes. Perhaps dd:mm.xxx  would be less ambiguous.

**Comment by BilliTheKid** [comment]
@JerryBlack @saoron Mine seem to be fine now.

**Comment by JerryBlack** [comment]
@saoron @BilliTheKid My dates are still wrong after a few days. Last night I brought the SD card into the house and file copied the file I wanted because with the app, I couldn't get the expandable selection bar to select a larger time frame (on an iPhone) without strange frustrating inconsistent behaviour. The files has the wrong time and no location or speed info, although I have seen those in the past. The app was very slow to display anything but grey images of videos without a proper preview thumbnail although I was sitting inside the car.   A video I was able to upload  https://dride.io/clip/h1r42M2116jPSMOS3Faq     When in the processing stack is the location/speed added to the video?

**Comment by BilliTheKid** [comment]
@JerryBlack Yes I'm having issues with grey images on the thumbnails too. The app is slow and do is the connectivity, uploading to cloud and downloading to device
