### ISSUE TITLE
Firmware 1.2-beta-0 GPS & Speed not showing

### ISSUE THREAD

**Issue by BilliTheKid** [dride/dride-app-issues#34]
This is this mornings drive @saoron 
![Screenshot_20191129-113134](https://user-images.githubusercontent.com/56843472/69866403-db7f3800-129b-11ea-8f4b-4dbf2961bc8d.png)

**Comment by saoron** [comment]
How long before the coordinates appear?

**Comment by BilliTheKid** [comment]
@saoron They didn't appear.

**Comment by BilliTheKid** [comment]
![Screenshot_20191130-194758](https://user-images.githubusercontent.com/56843472/69905366-69e1df80-13aa-11ea-952e-c0b4102de67e.png)
GPS & Speed back working today @saoron

**Comment by BilliTheKid** [comment]
@saoron Since the last app update today GPS & speed has again disappeared. 
![Screenshot_20191204-222349](https://user-images.githubusercontent.com/56843472/70187287-b6e4ef00-16e5-11ea-9e67-c2af0197445e.png)

**Comment by saoron** [comment]
It might take some time for the GPS to catch enough satellites to determine your location, Connecting via the fuse box might help with keeping it in sync..

Closing.
