### ISSUE TITLE
Firmware 1.2-beta-0 Background connectivity issues

### ISSUE THREAD

**Issue by BilliTheKid** [dride/dride-app-issues#36]
There is constant issues with connecting to the app and showing the WiFi connected symbol. Sometimes I need to open the app to do other times it just doesn't connect. If app is closed in the background it will not connect at all. Didn't have this issue before (Android)

**Comment by BilliTheKid** [comment]
This issue is still here even with new app update. @saoron

**Comment by saoron** [comment]
Make sure you have only one device connected to the dashcam at all times..

**Comment by BilliTheKid** [comment]
Of course it one device is connected to the unit my device. Again not sure why you closed this it's still an issue. It's Ben reported by other users on the forum so it's not just me

**Comment by saoron** [comment]
I'm not sure the scenario you describing exist anymore, I could see you've uploaded videos and saw you have event videos on your phone..

**Comment by BilliTheKid** [comment]
@saoron As mentioned it doesn't always connect automatically. I need to force the connection by opening the app to do so even though the app is running in the background.

**Comment by saoron** [comment]
Why would you force a connection while it's in the background? It should disconnect when the app is minimized, that's expected so you could use your phone's internet.. It will automatically connect when it need to download a video..

**Comment by BilliTheKid** [comment]
@saoron Yes that's what it should do but it doesn't

**Comment by saoron** [comment]
If you have downloaded videos in your app it was the result of an automatic connection, There's simply no other way..
It knows to auto connect to the dashcam when it needs to download a video (Roughly every 15 minutes)
