### ISSUE TITLE
Firmware 1.2-beta-0 Deleting event videos

### ISSUE THREAD

**Issue by BilliTheKid** [dride/dride-app-issues#37]
There is still a bug when deleting event videos and they reappear again.

**Comment by BilliTheKid** [comment]
@saoron Still cannot delete events on current firmware and app.

**Comment by BilliTheKid** [comment]
With the newest app update today you still cannot delete videos with the reappearing again when the app is reopened. @saoron

**Comment by saoron** [comment]
Fixed on 6.1+
