### ISSUE TITLE
Firmware 1.2-beta-0 Sharing button not working

### ISSUE THREAD

**Issue by BilliTheKid** [dride/dride-app-issues#38]
When pressing the sharing button it only captured seconds of video. It states this video should automatically either upload to the cloud or download to the device which it doesn't.

**Comment by BilliTheKid** [comment]
Even on the latest app and firmware by pressing the share button only records seconds and does not upload to cloud as stated it would @saoron

**Comment by BilliTheKid** [comment]
Has this been looked into? That when you press the share button that it automatically uploads to cloud? @saoron

**Comment by BilliTheKid** [comment]
@saoron Any update on this?

**Comment by saoron** [comment]
You should press the button during driving, when the app is not opened, This might happen if the app was opened and you try to "test" it by pressing the share button. In normal use this shouldn't be a problem..

**Comment by BilliTheKid** [comment]
@saoron App is always closed and running in the background. Still an issue

**Comment by saoron** [comment]
Does it happens all the time or sometime?

**Comment by BilliTheKid** [comment]
@saoron It happens sometimes not all the time but there must be a bug

**Comment by saoron** [comment]
I'll keep an eye on this..

**Comment by BilliTheKid** [comment]
@saoron Can you tell me what the higher pitch chime indicates?

**Comment by saoron** [comment]
@BilliTheKid please upload a video so I could tell which one is it..

**Comment by BilliTheKid** [comment]
@saoron When I'm back in my car next I will record it. It seems to be doing this after switching from the beta to the public release.
