### ISSUE TITLE
Firmware 1.2 - videos not automatically recording

### ISSUE THREAD

**Issue by gaurav85** [dride/dride-app-issues#41]
Since the update to this firmware, my Dride wont save videos automatically. I have set my settings on a 3 minute length and each time I connect it with my app, I dont see any recordings besides the one when I connect my phone for 5 secs.

**Comment by saoron** [comment]
You need to give it time to record..

Try this:
- Unplug your dashcam
- Wait for 30 minutes
- Open the app and see if you have ~10 clips..

Let me know how it went..

**Comment by gaurav85** [comment]
> You need to give it time to record..
> 
> Try this:
> 
> * Unplug your dashcam
> * Wait for 30 minutes
> * Open the app and see if you have ~10 clips..
> 
> Let me know how it went..

Yossi, I did give it plenty of time each day to record. My drive to work usually takes anywhere between 20-30 mins.. I have the dashcam set to record at 3 mins interval. Most days, I only see one clip towards the end of the day when I try and connect my app to it. What I expect is to see all the recordings from the morning drive to work and then the drive back home.

**Comment by gaurav85** [comment]
@saoron any update on this. I am missing several events during the day when I drive. I sometimes have a few events from morning, completely misses out afternoon drive and then a few more from the evening. Never consistent.

**Comment by Mensra** [comment]
That’s been my experience as well

**Comment by gaurav85** [comment]
@saoron how do we update from firmware 1.2-beta 0 to the public release version. I tried putting the bin file on the SD card and it does not do anything when I boot up the device.

**Comment by saoron** [comment]
The public version is on GitHub releases: https://github.com/dride/dride-app-issues/releases/tag/1.2

**Comment by gaurav85** [comment]
@saoron yes, I did get that bin file from the link you just sent. I put it on the SD card and powered on the dashcam. It did nothing and the solid white light stayed on. How can I move from 1.2 beta to the public version?

**Comment by saoron** [comment]
@gaurav85 i've updated the file, could you please try now?

**Comment by gaurav85** [comment]
@saoron yes, the firmware upgrade worked now. I will test and update you with results.

**Comment by gaurav85** [comment]
@saoron i have the latest firmware. Please check the screenshot below that shows different timestamps from one trip that was 15 mins long. Timestamps are 1 hr apart.
![39C7B58B-46C0-4744-8672-CF0A416E7927](https://user-images.githubusercontent.com/8796616/70578013-276e8e80-1b72-11ea-9619-eddad091f04e.png)

**Comment by saoron** [comment]
How can you tell they're apart? The videos on the first row are "events" they appear when you click on the button, The videos below are the video stream. It looks like the last video was a few minutes before your screen shot, that's seems normal..

**Comment by gaurav85** [comment]
> How can you tell they're apart? The videos on the first row are "events" they appear when you click on the button, The videos below are the video stream. It looks like the last video was a few minutes before your screen shot, that's seems normal..

@saoron I pressed the button while driving at 17:16 but as you can see it shows as 16:16.  If you look further down the other videos also show as 16:18 which is also incorrect as these were also taken during my trip back from work after 17:15.

**Comment by gaurav85** [comment]
@saoron also, I am not the only one having these issues. You can look at the forums and other issues within GitHub and others are complaining about it as well.

**Comment by BilliTheKid** [comment]
@saoron @gaurav85 This is what I was trying to explain to you in the other thread. The event timestamps are incorrect when the share button is pushed.

**Comment by gaurav85** [comment]
> @saoron @gaurav85 This is what I was trying to explain to you in the other thread. The event timestamps are incorrect when the share button is pushed.

@BilliTheKid @saoron For me its just not the event timestamps, even the videos around the time of the button press have incorrect timestamps.

**Comment by BilliTheKid** [comment]
@gaurav85 @saoron I decided to flash the firmware again. It seemed to have sorted out the event timestamp and on device too. Although you cannot delete events without them reappearing so this is still a bug that hasn't been squashed.
![Screenshot_20191211-202835](https://user-images.githubusercontent.com/56843472/70657955-d4b9d300-1c54-11ea-85a6-0c4b62966c28.png)

**Comment by gaurav85** [comment]
@saoron tried reflashing the firmware and now the timestamps are more messed up. Also, for my 20 min ride after flashing, I have only two videos when I set the recording length to 1 min. See the screenshot.
![BA771738-582A-48B9-93B4-71F6A1B4B87E](https://user-images.githubusercontent.com/8796616/70661572-2dc04180-1c2a-11ea-97b3-fdb2fd8eca43.png)

**Comment by BilliTheKid** [comment]
@gaurav85 New app has just been released 6.1.1 Try that. Delete all videos and try again.

**Comment by gaurav85** [comment]
> @gaurav85 New app has just been released 6.1.1 Try that. Delete all videos and try again.

Not for iOS yet 😟

**Comment by BilliTheKid** [comment]
@gaurav85 Must be an issue with the IOS app then I'd say.

**Comment by gaurav85** [comment]
@BilliTheKid i meant the iOS update is not out yet. Also, may be timestamps is an issue with iOS but mine doesn't even store videos consistently. I only get 1-2 videos for an entire trip irrespective which video length I set.

**Comment by BilliTheKid** [comment]
@gaurav85 Im sure the update is on its way for iOS

**Comment by gaurav85** [comment]
@saoron timestamps 12hrs ahead
![17099415-FA66-4FED-A506-4A1306C35899](https://user-images.githubusercontent.com/8796616/70808114-9cb1ad80-1d84-11ea-956f-3a8857cb45f7.png)

**Comment by gaurav85** [comment]
@saoron i can confirm the timestamp and videos not recording for all events now seems to be fixed with latest app update and firmware 1.3.

**Comment by BilliTheKid** [comment]
Yes can confirm time stamp on events seems to be fixed. Will monitor.
