### ISSUE TITLE
Android Dride App v6.00

### ISSUE THREAD

**Issue by BilliTheKid** [dride/dride-app-issues#44]
Great to see some improvements with the new app. I recieve notifications when the button is pressed to say the video is downloading. Then I receive another notification to state the video is ready to upload. Please press here to upload. When I do it takes a good few seconds to open the app but it does not direct me to the clip that was downloaded or start to upload automatically as the push notification would have you believe. Issue still with deleting events video clips and returning again.
Uploading to cloud still results in errors. (See attached) Also there seems to be intermediate issues with the thumbnail clips displaying on events (See attached) There still seems to be a bug connecting to the app. Sometimes I need to open the app for it to connect even though the app is still running in the background. This might be the result of the Red banner click to connect possibly. Time stamping is now fixed after deleting all previous videos stored. I'd still like to see an option to change date format for people in different regions. US users would have month, day, year, while EU users would have day, month, year. Currently it's set to year, month, day.
Pick up on GPS satellites seems alot faster.
I'd still like to see the sync sharing button fixed. To have the video automatically upload in the background when pressed and also the issue that I stated above. Other than that it's performing great. I hope you can iron out the last remaining bugs mentioned. @saoron 
![Screenshot_20191209-115620](https://user-images.githubusercontent.com/56843472/70437782-47c01f80-1a84-11ea-87b1-406a29dfcb5b.png)
![Screenshot_20191209-122928](https://user-images.githubusercontent.com/56843472/70437791-4ee72d80-1a84-11ea-9684-a086cb834ff7.png)
![Screenshot_20191209-122945](https://user-images.githubusercontent.com/56843472/70437798-5575a500-1a84-11ea-8951-217ec835f813.png)

**Comment by saoron** [comment]
Many issues that were reported was fixed in v6+,
thanks
