### ISSUE TITLE
Uploading saved events to Dride cloud

### ISSUE THREAD

**Issue by BilliTheKid** [dride/dride-app-issues#46]
@saoron As you can see I have 2 saved videos. When I'm disconnected from the dashcam and on my home network it will not upload to Dride cloud and repeatedly giving an error. You said you should be able to upload to cloud when not connected to the unit itself.
![Screenshot_20191210-154318](https://user-images.githubusercontent.com/56843472/70544518-1c146680-1b64-11ea-8d1a-6a3de94c1a13.png)
![Screenshot_20191210-154239](https://user-images.githubusercontent.com/56843472/70544536-22a2de00-1b64-11ea-87b6-a98bb7498ea1.png)
![Screenshot_20191210-154304](https://user-images.githubusercontent.com/56843472/70544542-26cefb80-1b64-11ea-9426-05b17e0b4398.png)

**Comment by BilliTheKid** [comment]
Currently on latest public firmware and app.
![Screenshot_20191210-150719](https://user-images.githubusercontent.com/56843472/70544649-53831300-1b64-11ea-93b3-fd3b41a4cfbf.png)

**Comment by saoron** [comment]
A fix is on it's way (v6.1)

**Comment by BilliTheKid** [comment]
Great. Thanks for letting me know. @saoron

**Comment by JerryBlack** [comment]
@saoron could you add a comment here when that is available for the iPhone as well.  Thanks.

btw, my dride stopped showing its network. A paper-clip reset fixed that, and brought back video with the correct date/time :)

**Comment by saoron** [comment]
Fixed on the latest app release..
