### ISSUE TITLE
Issues after changing from beta to public firmware release

### ISSUE THREAD

**Issue by BilliTheKid** [dride/dride-app-issues#47]
After updating today from the beta to the public release (which was a little painful) some issues have arisen. (Full hard reset had to be done twice to the unit)

• When pressing the sharing button it gave off a higher pitch chime than usual. (Strange) but no push notification was presented to me that it was downloading the event. I tried a few more times resulting in the same higher pitched chime and then my Dride just froze. Even after turning the engine off it was still on. Hard reset had to be done to rectify this. But nothing was captured and no push notifications. It seemed to work before updating to public release.

• Events time are playing up again.. As you can see the videos on device are fine but the event timing is not. Again didn't have this issue on the beta and only has occured when I switched to public firmware. I think you should just let users set their own times/date format etc.

@saoron 
![Screenshot_20191210-193148](https://user-images.githubusercontent.com/56843472/70565149-6825d200-1b89-11ea-99ae-dad7c09e3dbd.png)
![Screenshot_20191210-192322](https://user-images.githubusercontent.com/56843472/70565174-707e0d00-1b89-11ea-9d11-86bb0c551e0b.png)

**Comment by gaurav85** [comment]
@saoron my timestamps are completely messed up both on events and videos
![043769AF-10D7-4B9D-B11A-AAB344D59826](https://user-images.githubusercontent.com/8796616/70630957-09e10980-1bf2-11ea-958e-b3c33ef77d73.png)

**Comment by BilliTheKid** [comment]
@gaurav85 How are you able to view your videos with no connection to your Dride? I don't see the WiFi connection.

**Comment by JerryBlack** [comment]
@BilliTheKid I believe that's the normal display using an iPhone. It appears (my guess) that if you have a WiFi connection to the dride (and it doesn't have a connection to the internet, i.e. it's not a router) then it shows the LTE connection you do have to the internet.

**Comment by BilliTheKid** [comment]
Ah ok. As you can see from my picture above it displays a WiFi connection when connected. By the way did you come off the beta and update to the public release?

**Comment by JerryBlack** [comment]
@BilliTheKid I'm not sure. I did a recent update. What it the link for the latest public release?

**Comment by BilliTheKid** [comment]
@JerryBlack Here you go. https://github.com/dride/dride-app-issues/releases
It wasn't easy updating. It won't flash on the card like the other betas. I was able to download the public release via the app but it's been playing up kinda since.

**Comment by JerryBlack** [comment]
@BilliTheKid Thanks. I did that one. I didn't notice the distinction that there was no beta in the release. I have the speed type option now,  app 6.01  firmware 1.2.

**Comment by JerryBlack** [comment]
@BilliTheKid I notice the wifi range is increased again, I'm just able to log-in while sitting in my living room, which is a nice plus (given it's snowing out) :)

**Comment by gaurav85** [comment]
> @gaurav85 How are you able to view your videos with no connection to your Dride? I don't see the WiFi connection.

@BilliTheKid yeah, thats the default display for iPhones when connected to a AdHoc network.

**Comment by gaurav85** [comment]
> @JerryBlack Here you go. https://github.com/dride/dride-app-issues/releases
> It wasn't easy updating. It won't flash on the card like the other betas. I was able to download the public release via the app but it's been playing up kinda since.

@BilliTheKid @JerryBlack yesterday, Yossi updated the build number so now it flashes correctly. I was not able to use my app to update from the beta.

**Comment by BilliTheKid** [comment]
Oh really? Wish he told me. Took 40 minutes to figure out it couldn't be done and to instigate the download via the app. Still a few bugs I've noticed though. Time stamp wrong again for events, share button not performing properly and push notifications for the share button only work sometimes.

**Comment by BilliTheKid** [comment]
@saoron Why did you close this thread? There are issues outlined above that need fixing and haven't been answered. For instance what is the higher pitch chime representing and time stamp out again.

**Comment by BilliTheKid** [comment]
6.1.0 has not resolved them issues @saoron

**Comment by gaurav85** [comment]
@BilliTheKid @saoron I was wondering the same thing. This thread describes all the ongoing issues with the new firmware. We all are experiencing these issues.

**Comment by saoron** [comment]
There's no way to track this thread since it hold many different issues and sometimes goes offtopic,
I'll add an issue template to make sure we stay focused. I read all issues and address them.

Your help is greatly appreciated.
