### ISSUE TITLE
Android v 6.1.0 issues.

### ISSUE THREAD

**Issue by BilliTheKid** [dride/dride-app-issues#49]
The uploading of saved events can now be uploaded to Dride cloud from your own network/WiFi

There was no developer log for this release so not sure what over changes have been done.

Issues still:

• Push notifications seems to be broken. Not getting them when the share button is pressed.(Possible server side issue)

• High pitch chime still present when pressing the sync button. Not the usual chime sound. Again does nothing. It did when I was on beta,
but switching to the public firmware update has stopped it. Not sure if this is a server side issue.

• Event video clips are 1 hour behind. Deleted all videos to retest the new app release and it's still the same. (See attached)

• After trying to press and capture events using the sync button the unit freezes. No sound when I press the button and when I turn the engine off the white light is still on. Pin reset is required to turn the unit off. Twice now this has occurred.

@saoron 

![Screenshot_20191211-093808](https://user-images.githubusercontent.com/56843472/70613701-043ef000-1c01-11ea-8d60-632fef698a59.png)
![Screenshot_20191211-102118](https://user-images.githubusercontent.com/56843472/70613707-0903a400-1c01-11ea-907d-0721d7705158.png)

**Comment by BilliTheKid** [comment]
Update:

After many hard resets (Do I need to be doing this all the time?) the normal chime tone is back.
I pressed the share button and the push notification came up. It stated it is downloading the clip, I got a further notification to say it was done to press the notification to share but when you do it does nothing. Doesn't bring you to the video clip. When I went back into the app the clip it stated it downloaded wasn't even there. Pressed the sync button again and no push notification came this time. There must be a bug somewhere.

**Comment by saoron** [comment]
1. The notification is not immediate, it might take time until the phone will decide to download the video.
2. When you tap on the notification it will open the app, you will see your freshly download video first the feed.

How can you tell the event video time is one hour ahead?

**Comment by BilliTheKid** [comment]
@saoron I have tested the share button about 10 times today. Out of the 10 times you got the notification only once. Also when you press the notification it does not for me being me yo the fresh download.

She attached for timestamp. Seems others are noticing it too.
![Screenshot_20191211-093808](https://user-images.githubusercontent.com/56843472/70640676-39186a80-1c34-11ea-915f-0ee21b648881.png)

**Comment by BilliTheKid** [comment]
![Screenshot_20191210-193148](https://user-images.githubusercontent.com/56843472/70640720-4a617700-1c34-11ea-862f-d4d23d588eea.png)

**Comment by BilliTheKid** [comment]
Also what does the higher pitch tone represent?

**Comment by saoron** [comment]
@BilliTheKid what's the problem with the timestamps?

**Comment by BilliTheKid** [comment]
@saoron The pictures above show you the issues.

**Comment by BilliTheKid** [comment]
![Screenshot_20191210-192322](https://user-images.githubusercontent.com/56843472/70643407-da092480-1c38-11ea-847d-280ec8d7e614.png)
![Screenshot_20191210-192322](https://user-images.githubusercontent.com/56843472/70643419-dfff0580-1c38-11ea-984c-206a85b32b7c.png)

**Comment by BilliTheKid** [comment]
#
![Screenshot_20191210-193148](https://user-images.githubusercontent.com/56843472/70643471-f73df300-1c38-11ea-94c6-ccab006f827e.png)

**Comment by BilliTheKid** [comment]
![Screenshot_20191210-192322](https://user-images.githubusercontent.com/56843472/70643500-01f88800-1c39-11ea-8357-62dd109e9676.png)

**Comment by saoron** [comment]
@BilliTheKid are they?

**Comment by BilliTheKid** [comment]
@saoron Yes. The event time stamp is completely out to the on the device stamp.

**Comment by saoron** [comment]
How can I know when did you press the button?..

**Comment by BilliTheKid** [comment]
I'm not talking about pressing the button in this thread it's related to when I open the app and the event clips timestamp is not correct

**Comment by saoron** [comment]
Well the timestamp is determined by the time you pressed the button...

**Comment by BilliTheKid** [comment]
Well if that's the case then the timestamp it's producing is not correct. Can you just let the user manually set the time and date format from within the app?
