### ISSUE TITLE
Dashcam freezes when pressing share button (Bug) 6.1.2

### ISSUE THREAD

**Issue by BilliTheKid** [dride/dride-app-issues#55]
Having an issue with this. Unit completely froze on me 3/4 times from using the share button which resulted in the unit being semi bricked. Only a pin slot reset would bring the unit back to life. This is a little worrying that this happens when I'm driving. It means I need to pull over and hard reset it. Not good in a situation if I'm in an accident and the unit has semi bricked. Seems to only happen when using the share button. So definitely something up I'd say with the firmware and needs investigating a.s a.p.

@saoron

**Comment by saoron** [comment]
What symptoms make you call it "frozen" how it reacts?

**Comment by BilliTheKid** [comment]
> What symptoms make you call it "frozen" how it reacts?

When you try and press the share button noting happens. When you turn off the power it is still on running on the internal battery, when you pen the app it won't connect and kicks back an error stating to reset unit or format memory card. It semi bricks and the only solution is to pin hole reset it. Few times this has happened now.
