### ISSUE TITLE
Deleting all videos doesn't work

### ISSUE THREAD

**Issue by szath75** [dride/dride-app-issues#56]
I went into Settings and tried to "Delete all videos".
I don't know if it erased any video, but I still can see there are video inside the dashcam memory.

**Comment by BilliTheKid** [comment]
> I went into Settings and tried to "Delete all videos".
> I don't know if it erased any video, but I still can see there are video inside the dashcam memory.

After the firmware update and app 6.2.2 can you still not delete videos?

**Comment by szath75** [comment]
I updated the app, but I can't connect to the device (See Issue #48), so I can't test.

**Comment by BilliTheKid** [comment]
> I updated the app, but I can't connect to the device (See Issue #48), so I can't test.

There is no issue deleting all videos or individual events on Android with firmware 1.3 and app 6.4

**Comment by szath75** [comment]
Since I can't connect to the device I couldn't upgrade the firmware to 1.3. I need to know how to upgrade it manually.

**Comment by BilliTheKid** [comment]
> Since I can't connect to the device I couldn't upgrade the firmware to 1.3. I need to know how to upgrade it manually.

Yes. Click code on the top left and then releases and download the bin file. Put it on your SD card and put it into the Dride. Strange you cannot connect to the Dride. Have you tried resetting the unit with a pin? Unistalling the app and reinstalling it again?

**Comment by szath75** [comment]
Thanks, I updated the firmware, but I still can't connect to try. I tried all until now.

**Comment by szath75** [comment]
Today I was able to connect once to the camera, I tried to delete all videos and it worked.

**Comment by BilliTheKid** [comment]
> Today I was able to connect once to the camera, I tried to delete all videos and it worked.

Cool. Close off this issue so.
