### ISSUE TITLE
Have to reset Dride to connect to phone via wifi

### ISSUE THREAD

**Issue by MyDefender** [dride/dride-app-issues#6]
Using the latest version of the iOS app. The app hangs on the ‘connecting’ screen. I have to reset the Dride (press and hold the button on it) before I can connect to it via WiFi. This happens every time. It was fine on the previous version of the app. I’ve tried uninstalling the app and reinstalling it.

**Comment by saoron** [comment]
@MyDefender have you tested this on the new version? (5.6.2)

**Comment by MyDefender** [comment]
Yes. Same issue.

**Comment by saoron** [comment]
Could you please upload a video of the whole connection process?

**Comment by Mensra** [comment]
I am having the same issue.
