### ISSUE TITLE
Feature requests for Dride

### ISSUE THREAD

**Issue by BilliTheKid** [dride/dride-app-issues#61]
• To be able to enable/disable the start up/shutdown chime on dride.
@saoron

**Comment by MyDefender** [comment]
To be able to flip rear video both horizontally and vertically.

**Comment by BilliTheKid** [comment]
I'm looking to get the rear camera for my Dride @saoron When will they be available to buy and I'm sure with all the help we have provided you will offer a discount code towards the sale?

**Comment by BilliTheKid** [comment]
Closing this as it seems it's not been noticed or responded too.
