### ISSUE TITLE
Firmware 1.3 long time to boot-up and unable to change resolution

### ISSUE THREAD

**Issue by MyDefender** [dride/dride-app-issues#63]
My Dride now takes 35 seconds to boot up and has red flashing lights each time, see video: [Movie_7075.zip](https://github.com/dride/dride-app-issues/files/4012771/Movie_7075.zip)

I'm on Firmware 1.3 and 6.4.0 iOS app.
I've tried resetting it using a pin. 

Also, unable to change the resolution since updating to FW 1.3; it's greyed out:
![IMG_7077](https://user-images.githubusercontent.com/56696655/71622983-52785b00-2bd1-11ea-8e2d-96bc75690629.PNG)

![IMG_7076](https://user-images.githubusercontent.com/56696655/71622998-6b810c00-2bd1-11ea-81e4-de9830b43a74.PNG)

**Comment by saoron** [comment]
Please remove the firmware file from the SD card, then it will boot normally.
Regarding the resolution settings, when the rear camera is connected the resolution is fixed on FullHD/FullHD

**Comment by MyDefender** [comment]
I updated the FW via the app so expected the FW file to be automatically deleted!

**Comment by saoron** [comment]
Sorry about that, it's a bug we're going to fix in the next version..
