### ISSUE TITLE
Parking Mode Bug (v1.4) (6.5.0)

### ISSUE THREAD

**Issue by BilliTheKid** [dride/dride-app-issues#66]
Looking into using parking mode. When turned on within the app and after turning the ignition off the unit remains on. After 15 mins I went back out to the car and the unit was still on (white light) I decided to start up the power in my car but the unit would not connect back to the app. I tried a few times but getting an internal error. The only thing I could do was to pin reset. After that was able to connect to the app and turn parking mode off. There seems to be a bug with it.

Also how does parking mode meant to work powered by USB?

@saoron

**Comment by saoron** [comment]
Parking mode requires a fuse box cable to operate..

**Comment by BilliTheKid** [comment]
But here is obviously a bug with it freezing like I mentioned. Why did you close the thread? @saoron
