### ISSUE TITLE
DrideOS N1.4 firmware

### ISSUE THREAD

**Issue by MyDefender** [dride/dride-app-issues#67]
So, I installed N1.4 by removing the SD card and doing it on my pc because it was stuck on 'Cleaning' when I tried to do it via the app. I’ve removed the bin file, but now the app won’t connect to the camera. It is stuck on ‘Connecting’! Argh!!!

**Comment by BilliTheKid** [comment]
Mmmm. Had no issue updating.

**Comment by saoron** [comment]
This was fixed on the latest app update.
