### ISSUE TITLE
Videos are upside down for some users

### ISSUE THREAD

**Issue by saoron** [dride/dride-app-issues#7]
This issue was reported on the Dride forum:

http://localhost:4200/forum/all-of-my-videos-are-upsidedown____rQdCo09lqsPhaXI2261U

---

A firmware fix is coming..

**Comment by BilliTheKid** [comment]
Confirm no issues with video being upside down

**Comment by BilliTheKid** [comment]
After flashing latest firmware it does fix many of the other issues but unfortunately the image is still inverted.

**Comment by BilliTheKid** [comment]
This is now fixed with latest firmware update
