### ISSUE TITLE
Searching for Device since updating to 5.6.4

### ISSUE THREAD

**Issue by trancen** [dride/dride-app-issues#8]
Running Android Pixel 3 XL, 10.x  

Ever since updating my version to 5.6.4 I haven't been able to connect to my 2 Driods cams. It just stays on "Searching for Device"

**Comment by saoron** [comment]
Hi @trancen, this was fixed on 5.7, could you please verify?

**Comment by trancen** [comment]
I cleared the cache and unstalled the app in 5.6.4 and it worked.
