### ISSUE TITLE
Delete doesn't Delete the Event recordings

### ISSUE THREAD

**Issue by trancen** [dride/dride-app-issues#9]
When I delete a Event recording in 5.7 Android and other older versions it doesn't delete the file after leaving the screen... I Delete the video, looks to be deleted. Goto settings for example and back to the videos and the 'deleted' video it back.

**Comment by BilliTheKid** [comment]
+1 yes can vouch for this bug. Press delete, it looks deleted but when you come out and back into the events it appears again @saoron

**Comment by saoron** [comment]
Confirmed, Will be fixed on the next app release.

**Comment by saoron** [comment]
Fixed and released in version 5.8.1 of the app. 

Thanks for reporting..
